### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'generate_restrict_tokens'

### ISSUE THREAD

**Issue by vigilante16** [syr-cn/ReactXT#1]
尝试运行 run_action.sh，出现以下报错
Traceback (most recent call last):
  File "main.py", line 153, in <module>
    main(get_args())
  File "main.py", line 33, in main
    model = Blip2Model(args)
  File "/sshfs/chenzhe/code/patent/ReactXT/model/blip2_model.py", line 92, in __init__
    self.blip2opt = Blip2OPT(args.bert_name, args.gin_num_layers, args.gin_hidden_dim, args.drop_ratio, args.tune_gnn, not args.not_tune_qformer, args.num_query_token, args.cross_attention_freq, args.llm_tune, args.peft_dir, args.opt_model, args.prompt, args)
  File "/sshfs/chenzhe/code/patent/ReactXT/model/blip2_opt.py", line 225, in __init__
    self.generate_restrict_tokens = args.generate_restrict_tokens
AttributeError: 'Namespace' object has no attribute 'generate_restrict_tokens'

**Comment by syr-cn** [comment]
This problem is caused by some missing argparse arguments. It has already been fixed.

Thanks for pointing out.
